### PR TITLE
Fix previous NIP-10 issues

### PR DESCRIPTION
**Pull request by arthurfranca**
fix [this comment](https://github.com/nostr-protocol/nips/pull/310#issuecomment-1451130539).

I would like to address [#293](https://github.com/nostr-protocol/nips/pull/293) and [#267](https://github.com/nostr-protocol/nips/issues/267) too. It would be good to center discussion on your PR as other issues are targeting the same file.

### CODE REVIEW

**Comment by arthurfranca** [comment]
@alexgleason please merge this PR so that the conversation may continue on nostr repository. By doing it your branch will include the sum of the solutions to current issues regarding same NIP.

**Comment by alexgleason** [comment]
You should open a separate MR with these changes. I'm not confident about the direction after the last comment in https://github.com/nostr-protocol/nips/pull/310#issuecomment-1451130539

**Comment by arthurfranca** [comment]
I think the comment you mention shows @mikedilger, a nostr client developer, is worried of losing the ability to request all thread at once, which currently needs the root marker.
But [#267](https://github.com/nostr-protocol/nips/issues/267) was converging to a new standard that would still allow for that kind of query, without the root marker.

I think i also addressed another worry of removing deprecated standards/drafts text by linking to NIP-10 file git history on the footnote.

**Comment by arthurfranca** [comment]
The goal was to merge all the fixes together here, because all changes touched the same file, creating file conflicts and uncertainties about what PR to accept, which would possibly lead to no accepted PRs.

I understand if you don't want to merge. Although your original PR would still be reviewed at nostr repo, open to further discussions.

**Pull request closed without merging**
